dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: channelape-github
    token:
      secure: ULLU+ZxtdE7jBANvq2kx53GA0tkfOUdmkZMp49pFcVX8SmjnNlrmyO/pt6iXaZ/ifOgKqk4fiaYXxJdnUX7daIaYS4fx2mGn2Nn1DJpSwndakYGWo/kOz3UbWNmrJO/bINNKWe0aMOUoyvKALTyp3VsJhJujY/CIU9Klrg7T6mbHWLejrJDGt2pc4D97ki5zYO3q6JumgKbgsfVQjGgyVmN6ADb7HHLoBS1HdJ1baO+J12oyCcek6Q6HBmM9ziw52gTV1eAAx+yQehz1RIWI2h3IwHMEJHkleSosfYeN+8wEmJajHSDXoj3S2VEzZN+7LnpAHgrFGLfofuZAsqxKrbvVL874B3eJEz+vKzTPLx7H72wq8oWP4pem0YMWtgankvch1Gz1w7YLsfU+CFx6udPXbFb9VWy6YO8Ut57w4F6iCz+27gKaqQfg0UIK63Y/3ThW/OMRheJVXnZ461NE8FQAtI8moUJOhntZP0bjU9CwhXYx1Vxef92TcApX4pp1ZbniIUvug17sSExCs+MRzqTUmsW4LRZFz+gMUwlMxm25gfN6ndX6PBVVOSS3L0R2ApARbS/TzzAe6gAXgtqBjFuTsACcU6xfWwXknqOFCuKWBa0JB/ku/fFVAr/O8yc5OKCLjYgbRMmjYFHq7DMJX4Spxx2udLQucchvfF65RyA=
language: node_js
node_js:
  - 8.10.0
jdk:
  - oraclejdk8
install:
  - npm install
script:
  - npm test
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash .travis/overwrite-sonar-project-version.sh; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi
cache:
  directories:
    - node_modules
    - "$HOME/.sonar/cache"
deploy:
  - provider: npm
    skip_cleanup: true
    email:
      - "$NPM_EMAIL"
    api_key:
      - "$NPM_TOKEN"
    tag: develop
    on:
      branch: develop
  - provider: npm
    skip_cleanup: true
    email:
      - "$NPM_EMAIL"
    api_key:
      - "$NPM_TOKEN"
    tag: latest
    on:
      branch: master